### PR TITLE
Ensure Authorization Server support Authorization Code Flow when Credential Offer requires it.

### LINKED ISSUE #373: NPE when authorization_endpoint is missing
If Authorization Server Metadata does not contain `authorization_endpoint`, AuthorizationEndpointClient will throw a null pointer exception on line `authorizationServerMetadata.authorizationEndpointURI.toURL()`.

### PR DESCRIPTION
**Pull request by dzarras**
Closes #373

### CODE REVIEW

File: src/main/kotlin/eu/europa/ec/eudi/openid4vci/CredentialOfferRequestResolver.kt [hunk 1]
```diff
@@ -32,6 +32,11 @@ data class CredentialOffer(
 ) : Serializable {
     init {
         require(credentialConfigurationIdentifiers.isNotEmpty()) { "credentials must not be empty" }
+        if (null == grants || grants is Grants.AuthorizationCode) {
```
Comment (babisRoutis) [inline src/main/kotlin/eu/europa/ec/eudi/openid4vci/CredentialOfferRequestResolver.kt:35]: Why the `null == grants` check?

File: src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DefaultCredentialOfferRequestResolver.kt [hunk 2]
```diff
@@ -103,6 +103,15 @@ internal class DefaultCredentialOfferRequestResolver(
         val grants = credentialOffer.grants?.toGrants(credentialIssuerMetadata)
         val authorizationServer = grants?.authServer() ?: credentialIssuerMetadata.authorizationServers[0]
         val authorizationServerMetadata = fetchAuthServerMetaData(authorizationServer)
+        if (null == grants || grants is Grants.AuthorizationCode) {
```
Comment (babisRoutis) [inline src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/DefaultCredentialOfferRequestResolver.kt:106]: Why the `null == grants` check?

**Review by babisRoutis — DISMISSED** [review]
@dzarras I am not sure about the `grants == null` check that appears in couple places.

The spec states the following:

> If grants is not present or is empty, the Wallet MUST determine the Grant Types the Credential Issuer's Authorization Server supports using the respective metadata


Currently, we don't support this functionality in our library, and certainly the absence of `grants` cannot be translated as a value that default to the authorization code grant.
